### ISSUE TITLE
Does this module compile Sightly/HTL template with JSON/JS to generate HTML data

### ISSUE THREAD

**Issue by rrawat-dev** [adobe/htlengine#41] opened 2019-02-15 09:10 UTC
Would it be possible for you to provide some examples on how to use this module, as I am a Front End developer and have landed on this page in search of compiling Sightly/HTL templates with javascript/json object to generate HTML.

**Comment by tripodsan** [comment] 2019-02-18 01:32
yes. see https://github.com/adobe/htlengine/blob/master/test/engine_test.js

I have never tried to run it in a browser. so far only nodejs is tested.

**Comment by rrawat-dev** [comment] 2019-02-20 04:00
I tried an example on mu local machine with following template code:

`const engine = require('@adobe/htlengine/src/main');
const template = '<p data-sly-unwrap>Hello World</p>';
const GLOBALS = {};
engine(GLOBALS, template).then(function(ret) {
    console.log('>>>> ', ret.body);
});`

Its giving following error:
`(node:9777) UnhandledPromiseRejectionWarning: Error: Plugin not implemented: unwrap
    at MarkupHandler._lookupPlugin (/Users/rakrawat/workspace/htlengine-test/node_modules/@adobe/htlengine/src/parser/html/MarkupHandler.js:391:11)
    at MarkupHandler._handlePlugin (/Users/rakrawat/workspace/htlengine-test/node_modules/@adobe/htlengine/src/parser/html/MarkupHandler.js:163:30)
    at MarkupHandler.onAttribute (/Users/rakrawat/workspace/htlengine-test/node_modules/@adobe/htlengine/src/parser/html/MarkupHandler.js:80:12)
    at tok.attributes.forEach (/Users/rakrawat/workspace/htlengine-test/node_modules/@adobe/htlengine/src/parser/html/HTMLParser.js:397:23)
    at Array.forEach (<anonymous>)
    at HTMLParser._processTag (/Users/rakrawat/workspace/htlengine-test/node_modules/@adobe/htlengine/src/parser/html/HTMLParser.js:396:22)
    at HTMLParser._update (/Users/rakrawat/workspace/htlengine-test/node_modules/@adobe/htlengine/src/parser/html/HTMLParser.js:154:35)
    at HTMLParser.parse (/Users/rakrawat/workspace/htlengine-test/node_modules/@adobe/htlengine/src/parser/html/HTMLParser.js:65:10)
    at Function.parse (/Users/rakrawat/workspace/htlengine-test/node_modules/@adobe/htlengine/src/parser/html/HTMLParser.js:60:36)
    at TemplateParser.parse (/Users/rakrawat/workspace/htlengine-test/node_modules/@adobe/htlengine/src/parser/html/TemplateParser.js:38:16)
(node:9777) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9777) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by tripodsan** [comment] 2019-02-20 05:54
`data-sly-unwrap`  is not implemented yet, it seems :-) 

I'll create a bug

**Comment by rrawat-dev** [comment] 2019-02-20 07:33
Can we use this npm module to create, validate and test HTL/Sightly templates at front end along with CSS, JavaScript and later consumed by AEM while running on an integrated environment.  

I mean, is it in sync with its AEM version for compiling HTL/Sightly templates or still directives/functionalities like data-sly-unwrap are to be incorporated.

**Comment by tripodsan** [comment] 2019-02-20 08:40
not really. the problem is, that the [HTL Scripting Engine](https://sling.apache.org/documentation/bundles/scripting/scripting-htl.html) used in AEM is tailored to be used serverside in a sling environment. it has many features that only apply to the way the runtime is handled in the sling engine. for example template-calls, resource includes, etc are very specific to how sling exposes the resources to the scripting engine. also, the global context, like the sling bindings, request, page, etc. are specific to sling. those global objects would not be present in this implementation.

best best you could do, is to validate if the template is syntactic correct (once it is spec compliant). if we provide the plugins for the missing features (like data-sly-include) that at least mimic some behaviour, and we provide a somewhat sensible runtime, you could use it to render an example output.

the question is: Why would you want to render the AEM HTL templates clientside or build time ?

**Comment by SunilSyal** [comment] 2019-02-20 15:02
Hey Tobias - the question that Rakesh asked is because we are building an application which has many components to be rendered at client side with API driven approach. So we want to leverage the same templates on both sides rather than duplicating the code for BE and FE.

**Comment by tripodsan** [comment] 2019-02-21 02:05
> is there any possibility that we can render it at client machine with any parser available?

do you mean in the browser? I haven't tried yet. most of the code isn't really nodejs specific. there are few calls to `fs`, but mostly in the runtime. I think using browserify or similar, and providing a browser specific runtime should work.

I would be more than happy for any contributions :-)

**Comment by tripodsan** [comment] 2019-04-10 08:40
closing for now.

**Closed by tripodsan** 2019-04-10 08:40 UTC
Labels: question
